### ISSUE TITLE
Collector leaderboard: Total Collected includes own inks

### ISSUE THREAD

**Issue by davidryan59** [BuidlGuidl/nifty-ink#2]
At the moment the Total Collected stat includes all inks owned by the collector.

Can we modify this so that the count excludes inks generated by the collector?

Although this can still be gamed, it will more accurately represent how many the collector has bought off other people.

In the screenshot below, probably 80% of these inks are self-minted, so the Total Collected stat should be a lot lower.

<img width="430" alt="total collected includes own inks" src="https://user-images.githubusercontent.com/11883046/131951402-25fe8698-d6eb-4d29-9a27-29afbad23f4f.png">

**Comment by davidryan59** [comment]
@azf20 thank you!

**Comment by azf20** [comment]
This should be fixed, but let me know if it doesn't work out (as it required some fixes in the subgraph!)

**Comment by davidryan59** [comment]
Thanks Adam!
