### ISSUE TITLE
Bug - like button on main page appears in front of wallet

### ISSUE THREAD

**Issue by davidryan59** [BuidlGuidl/nifty-ink#24]
On the main Nifty Ink page, the wallet appears over the top of everything else, except for the Like button:

<img width="664" alt="Screenshot 2021-11-28 at 10 20 42" src="https://user-images.githubusercontent.com/11883046/143727573-9cf9ed9d-c3b7-4213-9aae-c22304745db9.png">

Rearrange so that wallet is in front of Like button and the ink thumbnail.

**Comment by davidryan59** [comment]
@azf20 I'm happy to take this one. Currently don't have access to change assignee

Can label it "Bug"

**Comment by azf20** [comment]
Makes sense. I think we did some janky stuff with z-index for the like button

**Comment by davidryan59** [comment]
Just found same bug on the nifty.ink/ink page too:

<img width="211" alt="Screenshot 2021-12-01 at 10 26 22" src="https://user-images.githubusercontent.com/11883046/144166945-75ecef95-cf51-4cf8-9089-d3806fbfae2f.png">

**Comment by davidryan59** [comment]
After investigating:
- Ink zIndex = 90
- Wallet zIndex = 99
- Current Like Button zIndex = 99 (which is why it appears in front of wallet)

Tried altering zIndex of Like Button

zIndex = 89:
<img width="115" alt="zIndex 89" src="https://user-images.githubusercontent.com/11883046/144168840-0159420e-7a9b-42ab-b52c-11a17f3fe66e.png">

zIndex = 90:
<img width="80" alt="zIndex 90" src="https://user-images.githubusercontent.com/11883046/144168844-44205725-8fe9-4bf7-9698-d31916b54a8d.png">

zIndex = 98:
<img width="88" alt="zIndex 98" src="https://user-images.githubusercontent.com/11883046/144168846-8111bb1a-3938-4680-b523-6c95bb2d2b68.png">

zIndex = 99:
<img width="85" alt="zIndex 99" src="https://user-images.githubusercontent.com/11883046/144168847-3f23b7d4-282e-4183-b9e7-671c367701cb.png">

It appears that any 90 <= zIndex < 99 will give the correct result

Choose zIndex = 90 since that matches the Ink that is being liked (on the View Ink page).

**Comment by azf20** [comment]
Closed by #28, thanks @davidryan59 !
