### ISSUE TITLE
Speed control for animation

### ISSUE THREAD

**Issue by davidryan59** [BuidlGuidl/nifty-ink#3]
Currently when you press "Play", the animation progresses at a fixed rate until it is finished.

Some inks this is good, others it is too fast (e.g. lots of circles), and others it is too slow (when there is a lot of fine detail)

Some ideas to investigate the viability of:
- Speed slider to speed up or slow down animation, maybe from 0.1x to 10x current rates
- Pause, rewind, fast forward buttons to be able to examine the temporary animated ink content (which can get overwritten by the artist as animation progresses!)
- Or - a slider to control position of animation in the overall animation, like on a (for example) 3 minute 48 second music track from 0:00 to 3:48

**Comment by azf20** [comment]
Closing this as speed control was added here https://github.com/BuidlGuidl/nifty-ink/pull/13
There may still be some enhancements.
The more advanced ideas (pause / rewind / fastforward, slider of animation) would require reworking the underlying `react-canvas-draw`, so I think they should be split out
