### ISSUE TITLE
Bug: button to copy artist address is available on "artist" but not on "holdings"

### ISSUE THREAD

**Issue by davidryan59** [BuidlGuidl/nifty-ink#6]
On an artist's ink:
- if you click through their address directly under the ink, you get the "Copy" button to the right of their address
- if you click through their address on ownership of the ink (say on copy 1 of N) then the copy button is not available.

The same copy button should be available in both places.

@azf20 Adam any idea why holdings is shown in one of these places, and not the other?

**Comment by davidryan59** [comment]
OK, so artist has the button, and holdings does not. Compare these two:

https://nifty.ink/artist/0x8c8B07C2501b3A3b034202ba11f270cfE5F11c27

https://nifty.ink/holdings/0x8c8b07c2501b3a3b034202ba11f270cfe5f11c27

**Comment by azf20** [comment]
I don't think this inconsistency was an intentional decision. Fix looks good!
