### ISSUE TITLE
Clear button should always be available

### ISSUE THREAD

**Issue by davidryan59** [BuidlGuidl/nifty-ink#9]
At the moment when I have a very large drawing in the browser cache, and I reload the page, the Clear button is not available until the drawing has been displayed.

This is a problem when the drawing is so large that the browser hangs.

We want the Clear canvas button to work at all times, so that if there is a massive drawing in the browser cache, it can be cleared before it has drawn, as well as after.

<img width="1045" alt="Screenshot 2021-09-23 at 09 43 59" src="https://user-images.githubusercontent.com/11883046/134447795-ac4e84f6-c0ff-4332-bc4c-5b76d1b277a7.png">

**Comment by azf20** [comment]
This should now be the case, but please re-open if it doesn't meet your needs!
